### ISSUE TITLE
SP calculation attempt during composite jobs

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/ARC#138]
There seems to be some path for a composite job (at least a restarted composite job) that causes it to attempt to a sp calculation, which automatically triggers an error.  Might be related to ARC's troubleshooting recipes.  

After restart:  
Traceback (most recent call last):
  File "../../ARC.py", line 74, in <module>
    main()
  File "../../ARC.py", line 68, in main
    arc_object.execute()
  File "/Users/mattjohnson/RMGCODE/ARC/arc/main.py", line 619, in execute
    adaptive_levels=self.adaptive_levels)
  File "/Users/mattjohnson/RMGCODE/ARC/arc/scheduler.py", line 327, in __init__
    self.run_sp_job(species.label)
  File "/Users/mattjohnson/RMGCODE/ARC/arc/scheduler.py", line 716, in run_sp_job
    label))
arc.arc_exceptions.SchedulerError: run_sp_job() was called for O=COCOO which has a composite method level of theory

**Comment by alongd** [comment]
Thanks!! Should be solved by #139, let me know if the issue still persists
