### ISSUE TITLE
Why does ARC attempts to run species I did not ask for? (frequency scaling factors)

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/ARC#197]
_Originally posted by @NtuCheRoy in https://github.com/ReactionMechanismGenerator/ARC/issues/196#issuecomment-532226656_

--------------------------------------------------

I try to run hydrogen with sp job, but in the file I see that ARC go to run opt job for the molecules I didn't give, and cause submitting too much job in a sudden, so reach this QOS's job submission limitation.  Why ARC would want to run these opt job for these molecule and doesn't run the job I submitting in the yml file?
```
Using Theano backend.
ARC execution initiated on Tue Sep 17 06:29:57 2019

###############################################################
#                                                             #
#                 Automatic Rate Calculator                   #
#                            ARC                              #
#                                                             #
#   Version: 1.1.0                                            #
#                                                             #
###############################################################

The current git HEAD for ARC is:
    ccdb557aa3f369b0de24da9a84ce9f9c3ad6dbb8
    Sun Sep 15 21:43:52 2019 -0400


Starting project arc_demo_1

Considering the following job types: ['sp']


Using the following ESS settings:
{'qchem': ['local']}



Warning: Not using a fine grid for geometry optimization jobs




Warning: Not running rotor scans. This might compromise finding the best conformer, as dihedral angles won't be corrected. Also, entropy won't be accurate.


Using b3lyp/6-31g* for refined conformer searches (after filtering via force fields)
Using b3lyp/6-31g* for TS guesses comparison of different methods
Using b3lyp/6-31g* for geometry optimizations
Using b3lyp/6-31g* for frequency calculations
Using b3lyp/6-31g* for single point calculations
Using b3lyp/6-31g* for rotor scans



Warning: Could not determine appropriate Model Chemistry to be used in Arkane for thermochemical parameter calculations.
Not using atom energy corrections and bond additivity corrections!


Using b3lyp/6-31g*//b3lyp/6-31g* as a model chemistry in Arkane
Warning: :root:No frequency scaling factor found for model chemistry b3lyp/6-31g*. Assuming a value of unity. This will affect the partition function and all quantities derived from it (thermo quantities and rate coefficients).
Could not determine the harmonic frequencies scaling factor for b3lyp/6-31g* from Arkane.
Calculating it using Truhlar's method:






FREQ: A PROGRAM FOR OPTIMIZING SCALE FACTORS (Version 1)
                 written by
Haoyu S. Yu, Lucas J. Fiedler, I.M. Alecu, and Donald G. Truhlar
Department of Chemistry and Supercomputing Institute
University of Minnesota, Minnesota 55455-0431
CITATIONS:
1. I.M., Alecu, J. Zheng, Y. Zhao, D.G. Truhlar, J. Chem. Theory Comput. 2010, 6, 9, 2872-2887,
   DOI: 10.1021/ct100326h
2. H.S. Yu, L.J. Fiedler, I.M. Alecu,, D.G. Truhlar, Computer Physics Communications 2017, 210, 132-138,
   DOI: 10.1016/j.cpc.2016.09.004




starting ARC...


Considering the following job types: [u'opt', u'conformers', u'sp', u'1d_rotors', u'freq', u'fine']


Computing scaling factors at the b3lyp/6-31g* level of theory...



Using the following ESS settings:
{'qchem': ['local']}

Running job opt_a45 for C2H2
Running job opt_a46 for CH4
Running job opt_a47 for CO2
Running job opt_a48 for CO
Running job opt_a49 for F2
Running job opt_a50 for CH2O
sbatch: error: QOSMaxSubmitJobPerUserLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)
Error: The following command is erroneous:

Traceback (most recent call last):
  File "/global/homes/s/shcheng/ARC/ARC.py", line 76, in <module>
    main()
  File "/global/homes/s/shcheng/ARC/ARC.py", line 69, in main
    arc_object = ARC(input_dict=input_dict, project_directory=project_directory)
  File "/global/u2/s/shcheng/ARC/arc/main.py", line 405, in __init__
    self.check_freq_scaling_factor()
  File "/global/u2/s/shcheng/ARC/arc/main.py", line 1015, in check_freq_scaling_factor
    level, ess_settings=self.ess_settings, init_log=False)[0]
  File "/global/u2/s/shcheng/ARC/arc/utils/scale.py", line 108, in determine_scaling_factors
    ess_settings=ess_settings, job_types=job_types, allow_nonisomorphic_2d=True)
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 363, in __init__
    self.run_opt_job(species.label)
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 805, in run_opt_job
    job_type='opt', fine=False)
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 659, in run_job
    self.job_dict[label][job_type][job.job_name].run()
  File "/global/u2/s/shcheng/ARC/arc/job/job.py", line 805, in run
    self.job_status[0], self.job_id = submit_job(path=self.local_path)
  File "/global/u2/s/shcheng/ARC/arc/job/local.py", line 98, in submit_job
    stdout = execute_command(cmd)[0]
  File "/global/u2/s/shcheng/ARC/arc/job/local.py", line 43, in execute_command
    ' sbatch path required in the submit_command dictionary.'.format(e.message))
arc.arc_exceptions.SettingsError: The following command is erroneous:

To correct the command, modify settings.py
Tips: use "which" command to locate cluster software commands on server.
Example: type "which sbatch" on a server running Slurm to find the correct sbatch path required in the submit_command dictionary.
```

**Comment by alongd** [comment]
Since ARC (more correctly, Arkane) does not have a frequency scaling factor for the level of theory you're using (`b3lyp/6-31g*`), it attempts to calculate it by spawning opt/freq/sp jobs for a set of 15 species (the Truhlar method). See Arkane's [supported model chemistries here](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#model-chemistry).

Note that ARC mentioned that:
```
Could not determine the harmonic frequencies scaling factor for b3lyp/6-31g* from Arkane.
Calculating it using Truhlar's method:
```

You can simply bypass this behaviour, as mentioned [in the documentation](https://reactionmechanismgenerator.github.io/ARC/advanced.html#frequency-scaling-factors):
Either pass a known frequency scaling factor using the freq_scale_factor attribute (see [examples](https://reactionmechanismgenerator.github.io/ARC/examples.html#examples)), or set the calc_freq_factor attribute to False (it is True by default).

For your case, since you're not trying to calculate thermo or rate coefficients, and you're not running frequencies, you'd probably want to specify `calc_freq_factor: false` in the input file.

**Comment by NtuCheRoy** [comment]
It works, thanks.
