### ISSUE TITLE
/bin/sh: -c: line 0: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by NtuCheRoy** [ReactionMechanismGenerator/ARC#198]
I meet another error. I have set up submit_command in arc/settings.py by below code.
```
submit_command = {'OGE': 'export SGE_ROOT=/opt/sge; /opt/sge/bin/lx24-amd64/qsub',
                  'Slurm': '/usr/bin/sbatch'}
```
I type `which sbatch` in my server, and it shows `/usr/bin/sbatch`, as same as that one in settings.py. I have no idea where is going wrong. Below is the trace message. 
```
Running job sp_a51 for hydrogen
/bin/sh: -c: line 0: syntax error near unexpected token `newline'
/bin/sh: -c: line 0: `/usr/bin/squeue -u <username>'
Error: The following command is erroneous:

Traceback (most recent call last):
  File "/global/homes/s/shcheng/ARC/ARC.py", line 76, in <module>
    main()
  File "/global/homes/s/shcheng/ARC/ARC.py", line 70, in main
    arc_object.execute()
  File "/global/u2/s/shcheng/ARC/arc/main.py", line 718, in execute
    dont_gen_confs=self.dont_gen_confs)
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 391, in __init__
    self.schedule_jobs()
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 413, in schedule_jobs
    self.get_servers_jobs_ids()  # updates `self.servers_jobs_ids`
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 1965, in get_servers_jobs_ids
    self.servers_jobs_ids.extend(check_running_jobs_ids())
  File "/global/u2/s/shcheng/ARC/arc/job/local.py", line 81, in check_running_jobs_ids
    stdout = execute_command(cmd)[0]
  File "/global/u2/s/shcheng/ARC/arc/job/local.py", line 43, in execute_command
    ' sbatch path required in the submit_command dictionary.'.format(e.message))
arc.arc_exceptions.SettingsError: The following command is erroneous:

To correct the command, modify settings.py
Tips: use "which" command to locate cluster software commands on server.
Example: type "which sbatch" on a server running Slurm to find the correct sbatch path required in the submit_command dictionary.
```

**Comment by alongd** [comment]
Could it be that you didn't specify your username on this server?
Your `servers` dictionary in settings.py should look like:
```python

servers = {
    'local': {
        'cluster_soft': 'Slurm',
        'un': 'shcheng',
    },
}
```

(I'm guessing from the trace above that `shcheng` is your username on the server)

**Comment by NtuCheRoy** [comment]
Yes!!! I solve it. Thank you so much!
