### ISSUE TITLE
KeyError: 'TS0' when running examples/rates_demo/input.yml

### ISSUE THREAD

**Issue by NtuCheRoy** [ReactionMechanismGenerator/ARC#199]
I ran the examples/rates_demo/input.yml as a test, and it happened a KeyError. Below is the trace message. Because I see `self.output[species.label]['restart'] += 'Restarted ARC at {0}; '.format(` `KeyError: u'TS0'`, I print the self.output and species.label out which are behind the trace message. Indeed, the key, TSO, is not in the dictionary, self.output, for H2O2.
By the way, it seems that it has no problem for some molecules, such as N2H4, NH, N2H3, NH2 labeled in input.yml. I just went to test the dehydrogenation of ethane (ethane <=> ethene + hydrogen), and it also happened `KeyError: u'TS0'` for finding rotor for ethane.
```
Using Theano backend.
ARC execution initiated on Wed Sep 18 09:07:26 2019
###############################################################
#                                                             #
#                 Automatic Rate Calculator                   #
#                            ARC                              #
#                                                             #
#   Version: 1.1.0                                            #
#                                                             #
###############################################################
The current git HEAD for ARC is:
    ccdb557aa3f369b0de24da9a84ce9f9c3ad6dbb8
    Sun Sep 15 21:43:52 2019 -0400


Starting project demo

Considering the following job types: ['opt', '1d_rotors', 'freq', u'fine', 'sp', 'conformers']


Using the following ESS settings:
{'onedmin': ['server1'], 'molpro': ['server2'], 'qchem': ['server1'], 'gaussian': ['local', 'server2']}

Using default level b3lyp/6-31g(d,p) EmpiricalDispersion=GD3BJ for refined conformer searches (after filtering via force fields)
Using default level b3lyp/6-31g(d,p) EmpiricalDispersion=GD3BJ for TS guesses comparison of different methods
Using default level wb97xd/def2tzvp for geometry optimizations
Using default level wb97xd/def2tzvp for frequency calculations
Using default level ccsd(t)-f12/cc-pvtz-f12 for single point calculations
Using default level wb97xd/def2tzvp for rotor scans
Using ccsd(t)-f12/cc-pvtz-f12//wb97xd/def2tzvp as a model chemistry in Arkane


Considering species: N2H4
<Molecule "NN">
Considering species: NH
<Molecule "[NH]">
Considering species: N2H3
<Molecule "N[NH]">
Considering species: NH2
<Molecule "[NH2]">
Considering species: c4rad
<Molecule "[CH]=CC=C">
Considering species: HO2
<Molecule "[O]O">
Considering species: c4birad
<Molecule "[CH]=C[C]=C">
Considering species: H2O2
<Molecule "OO">



Loading RMG's families...



Considering reaction: c4rad + HO2 <=> c4birad + H2O2
(identified as belonging to RMG family H_Abstraction, which is its own reverse)
c4rad + HO2 <=> c4birad + H2O2
Trying to generating a TS guess for H_Abstraction reaction c4rad + HO2 <=> c4birad + H2O2 using AutoTST...
Using Theano backend.
reaction.py:169 load_databases INFO Loading RMG database from '/global/u2/s/shcheng/RMG/RMG-database/input'
thermo.py:844 loadLibraries INFO Loading thermodynamics library from primaryThermoLibrary.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from CBS_QB3_1dHR.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:861 loadGroups INFO Loading thermodynamics group database from /global/u2/s/shcheng/RMG/RMG-database/input/thermo/groups...
transport.py:294 loadGroups INFO Loading transport group database from /global/u2/s/shcheng/RMG/RMG-database/input/transport/groups...
statmech.py:529 loadGroups INFO Loading frequencies group database from /global/u2/s/shcheng/RMG/RMG-database/input/statmech/groups...
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/R_Addition_MultipleBond/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/H_Abstraction/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/intra_H_migration/TS_groups.py
reaction.py:341 get_labeled_reaction INFO Matched reaction to H_Abstraction family
reaction.py:341 get_labeled_reaction INFO Matched reaction to H_Abstraction family
reaction.py:250 generate_distance_data INFO Distance between *1 and *3 is too small, setting it to lower bound of uncertainty
reaction.py:255 generate_distance_data INFO The distance data is as follows: DistanceData(distances={'d12': 1.431964,'d13': 2.406448,'d23': 1.106812,}, uncertainties={'d12': 0.428770,'d13': 0.245552,'d23': 0.337577,}, comment='Matched node Cd_Cds/Cd/H ([<Entry index=195 label="Cd_Cds/Cd/H">, <Entry index=17 label="Cj">])\nMatched node OjO ([<Entry index=126 label="C/H2/Cd/Cd">, <Entry index=32 label="OjO">])\n')
Traceback (most recent call last):
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 92, in <module>
    main()
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 79, in main
    positions = reaction.ts.ase_ts.get_positions()
AttributeError: 'dict' object has no attribute 'ase_ts'
Trying to generating a TS guess for H_Abstraction reaction c4rad + HO2 <=> c4birad + H2O2 using AutoTST in the reverse direction...
Using Theano backend.
reaction.py:169 load_databases INFO Loading RMG database from '/global/u2/s/shcheng/RMG/RMG-database/input'
thermo.py:844 loadLibraries INFO Loading thermodynamics library from primaryThermoLibrary.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from CBS_QB3_1dHR.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:861 loadGroups INFO Loading thermodynamics group database from /global/u2/s/shcheng/RMG/RMG-database/input/thermo/groups...
transport.py:294 loadGroups INFO Loading transport group database from /global/u2/s/shcheng/RMG/RMG-database/input/transport/groups...
statmech.py:529 loadGroups INFO Loading frequencies group database from /global/u2/s/shcheng/RMG/RMG-database/input/statmech/groups...
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/R_Addition_MultipleBond/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/H_Abstraction/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/intra_H_migration/TS_groups.py
reaction.py:341 get_labeled_reaction INFO Matched reaction to H_Abstraction family
reaction.py:341 get_labeled_reaction INFO Matched reaction to H_Abstraction family
reaction.py:250 generate_distance_data INFO Distance between *1 and *3 is too small, setting it to lower bound of uncertainty
reaction.py:255 generate_distance_data INFO The distance data is as follows: DistanceData(distances={'d12': 1.108432,'d13': 2.406223,'d23': 1.430548,}, uncertainties={'d12': 0.337116,'d13': 0.246053,'d23': 0.428882,}, comment='Matched node OOH ([<Entry index=29 label="OOH">, <Entry index=261 label="Cdj_CddH">])\nMatched node Cdj_CdsCd ([<Entry index=29 label="OOH">, <Entry index=263 label="Cdj_CdsCd">])\n')
Traceback (most recent call last):
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 92, in <module>
    main()
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 79, in main
    positions = reaction.ts.ase_ts.get_positions()
AttributeError: 'dict' object has no attribute 'ase_ts'



Considering reaction: N2H4 + NH <=> N2H3 + NH2
(identified as belonging to RMG family H_Abstraction, which is its own reverse)
N2H4 + NH <=> N2H3 + NH2
Setting multiplicity of reaction N2H4 + NH <=> N2H3 + NH2 to 3
Trying to generating a TS guess for H_Abstraction reaction N2H4 + NH <=> N2H3 + NH2 using AutoTST...
Using Theano backend.
reaction.py:169 load_databases INFO Loading RMG database from '/global/u2/s/shcheng/RMG/RMG-database/input'
thermo.py:844 loadLibraries INFO Loading thermodynamics library from primaryThermoLibrary.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from CBS_QB3_1dHR.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:861 loadGroups INFO Loading thermodynamics group database from /global/u2/s/shcheng/RMG/RMG-database/input/thermo/groups...
transport.py:294 loadGroups INFO Loading transport group database from /global/u2/s/shcheng/RMG/RMG-database/input/transport/groups...
statmech.py:529 loadGroups INFO Loading frequencies group database from /global/u2/s/shcheng/RMG/RMG-database/input/statmech/groups...
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/R_Addition_MultipleBond/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/H_Abstraction/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/intra_H_migration/TS_groups.py
Traceback (most recent call last):
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 92, in <module>
    main()
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 79, in main
    positions = reaction.ts.ase_ts.get_positions()
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 118, in ts
    for direction, complex in self.get_rmg_complexes().items():
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 517, in get_rmg_complexes
    self.get_labeled_reaction()
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 333, in get_labeled_reaction
    test_reaction.reactants, test_reaction.products)
  File "/global/homes/s/shcheng/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 2592, in getLabeledReactantsAndProducts
    mappingsB = self.__matchReactantToTemplate(moleculeB, template.reactants[1].item)
IndexError: list index out of range
Trying to generating a TS guess for H_Abstraction reaction N2H4 + NH <=> N2H3 + NH2 using AutoTST in the reverse direction...
Using Theano backend.
reaction.py:169 load_databases INFO Loading RMG database from '/global/u2/s/shcheng/RMG/RMG-database/input'
thermo.py:844 loadLibraries INFO Loading thermodynamics library from primaryThermoLibrary.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from thermo_DFT_CCSDTF12_BAC.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:844 loadLibraries INFO Loading thermodynamics library from CBS_QB3_1dHR.py in /global/u2/s/shcheng/RMG/RMG-database/input/thermo/libraries...
thermo.py:861 loadGroups INFO Loading thermodynamics group database from /global/u2/s/shcheng/RMG/RMG-database/input/thermo/groups...
transport.py:294 loadGroups INFO Loading transport group database from /global/u2/s/shcheng/RMG/RMG-database/input/transport/groups...
statmech.py:529 loadGroups INFO Loading frequencies group database from /global/u2/s/shcheng/RMG/RMG-database/input/statmech/groups...
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/R_Addition_MultipleBond/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/H_Abstraction/TS_groups.py
base.py:220 load INFO Loading transitions state family groups from /global/homes/s/shcheng/AutoTST/database/intra_H_migration/TS_groups.py
Traceback (most recent call last):
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 92, in <module>
    main()
  File "/global/u2/s/shcheng/ARC/arc/ts/run_autotst.py", line 79, in main
    positions = reaction.ts.ase_ts.get_positions()
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 118, in ts
    for direction, complex in self.get_rmg_complexes().items():
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 517, in get_rmg_complexes
    self.get_labeled_reaction()
  File "/global/homes/s/shcheng/AutoTST/autotst/reaction.py", line 333, in get_labeled_reaction
    test_reaction.reactants, test_reaction.products)
  File "/global/homes/s/shcheng/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 2592, in getLabeledReactantsAndProducts
    mappingsB = self.__matchReactantToTemplate(moleculeB, template.reactants[1].item)
IndexError: list index out of range

Found one possible rotor for N2H4
Pivot list(s) for N2H4: [[1, 2]]


Found one possible rotor for N2H3
Pivot list(s) for N2H3: [[1, 2]]


Found one possible rotor for c4rad
Pivot list(s) for c4rad: [[1, 2]]


Found 2 possible rotors for c4birad
Pivot list(s) for c4birad: [[1, 3], [1, 4]]


Found one possible rotor for H2O2
Pivot list(s) for H2O2: [[1, 2]]

Traceback (most recent call last):
  File "/global/homes/s/shcheng/ARC/ARC.py", line 76, in <module>
    main()
  File "/global/homes/s/shcheng/ARC/ARC.py", line 70, in main
    arc_object.execute()
  File "/global/u2/s/shcheng/ARC/arc/main.py", line 718, in execute
    dont_gen_confs=self.dont_gen_confs)
  File "/global/u2/s/shcheng/ARC/arc/scheduler.py", line 316, in __init__
    self.output[species.label]['restart'] += 'Restarted ARC at {0}; '.format(
KeyError: u'TS0'
```
self.output and species.label for H2O2: [[1, 2]]

```
self.output is: {'NH': {u'info': u'', u'paths': {u'composite': u'', u'freq': u'', u'sp': u'', u'geo': u''},
 u'isomorphism': u'', u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 'bde': True, 
u'onedmin': False, u'composite': False, u'fine': False, 'sp': False, '1d_rotors': True, 'orbitals': False, 
'freq': False, 'conformers': False}, u'convergence': False, u'conformers': u'', u'restart': u'Restarted 
ARC at 2019-09-18 09:44:37.264770; '}, 'c4birad': {u'info': u'', u'paths': {u'composite': u'', u'freq': 
u'', u'sp': u'', u'geo': u''}, u'isomorphism': u'', u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 
'bde': True, u'onedmin': False, u'composite': False, u'fine': False, 'sp': False, '1d_rotors': True, 
'orbitals': False, 'freq': False, 'conformers': False}, u'convergence': False, u'conformers': u'', 
u'restart': u'Restarted ARC at 2019-09-18 09:44:37.265836; '}, 'H2O2': {u'info': u'', u'paths': 
{u'composite': u'', u'freq': u'', u'sp': u'', u'geo': u''}, u'isomorphism': u'', u'warnings': u'', u'errors': 
u'', u'job_types': {'opt': False, 'bde': True, u'onedmin': False, u'composite': False, u'fine': False, 'sp': 
False, '1d_rotors': True, 'orbitals': False, 'freq': False, 'conformers': False}, u'convergence': False, 
u'conformers': u'', u'restart': u'Restarted ARC at 2019-09-18 09:44:37.266186; '}, 'c4rad': {u'info': 
u'', u'paths': {u'composite': u'', u'freq': u'', u'sp': u'', u'geo': u''}, u'isomorphism': u'', u'warnings': u'', 
u'errors': u'', u'job_types': {'opt': False, 'bde': True, u'onedmin': False, u'composite': False, u'fine': 
False, 'sp': False, '1d_rotors': True, 'orbitals': False, 'freq': False, 'conformers': False}, u'convergence': 
False, u'conformers': u'', u'restart': u'Restarted ARC at 2019-09-18 09:44:37.265421; '}, 'N2H4': 
{u'info': u'', u'paths': {u'composite': u'', u'freq': u'', u'sp': u'', u'geo': u''}, u'isomorphism': u'', 
u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 'bde': True, u'onedmin': False, u'composite': 
False, u'fine': False, 'sp': False, '1d_rotors': True, 'orbitals': False, 'freq': False, 'conformers': False}, 
u'convergence': False, u'conformers': u'', u'restart': u'Restarted ARC at 2019-09-18 
09:44:37.264134; '}, 'HO2': {u'info': u'', u'paths': {u'composite': u'', u'freq': u'', u'sp': u'', u'geo': u''}, 
u'isomorphism': u'', u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 'bde': True, u'onedmin': 
False, u'composite': False, u'fine': False, 'sp': False, '1d_rotors': True, 'orbitals': False, 'freq': False, 
'conformers': False}, u'convergence': False, u'conformers': u'', u'restart': u'Restarted ARC at 2019-
09-18 09:44:37.265715; '}, 'NH2': {u'info': u'', u'paths': {u'composite': u'', u'freq': u'', u'sp': u'', 
u'geo': u''}, u'isomorphism': u'', u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 'bde': True, 
u'onedmin': False, u'composite': False, u'fine': False, 'sp': False, '1d_rotors': True, 'orbitals': False, 
'freq': False, 'conformers': False}, u'convergence': False, u'conformers': u'', u'restart': u'Restarted 
ARC at 2019-09-18 09:44:37.265308; '}, 'N2H3': {u'info': u'', u'paths': {u'composite': u'', u'freq': u'', 
u'sp': u'', u'geo': u''}, u'isomorphism': u'', u'warnings': u'', u'errors': u'', u'job_types': {'opt': False, 
'bde': True, u'onedmin': False, u'composite': False, u'fine': False, 'sp': False, '1d_rotors': True, 
'orbitals': False, 'freq': False, 'conformers': False}, u'convergence': False, u'conformers': u'', 
u'restart': u'Restarted ARC at 2019-09-18 09:44:37.264914; '}}

species.label is: TS0
```

**Comment by alongd** [comment]
I think the issue here is that AutoTST isn't configured correctly.
ARC will soon support AutoTST and other TS methods, so I'm OK with this issue for now. If you just tried to run it to see that all examples work, then it's fine. If you really care about H abstraction TS's, then either run AutoTST separately for now (or generate the TS guess using any other method) and feed the guess into ARC, or wait until ARC fully supports TSs and reactions.
