### ISSUE TITLE
Scan calculation error: 'int' object not iterrable

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/ARC#471]
Hi @alongd,
This is for the problem when calculating scan jobs. Both the input and errorinfo files are attached. In this input file, I pass 'CBS-QB3' to arkane leveloftheory. So there is no problem from Arkane.
[COCinput.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7256677/COCinput.txt)
[COCerror.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7256678/COCerror.txt)

**Comment by alongd** [comment]
From the error log, it doesn't seem like the most updated version of ARC.
Could you update ARC on the server, unless it was just installed?
(to update, in the ARC folder type `git pull`)
Please let me know what's the top most commit you see whey you type `git log`.

**Comment by NUSCondy** [comment]
Indeed, it was not up to date. So I update the ARC codes. However, a lot of errors then showed up. Firstly, 'openbabel' could not be loaded. Then I also upgrade RMG and ARC environment in case it is then causing that. After all these steps, it is also a problem here.
FYI, the commit of ARC log is:
_commit 8220e6c1e66a92a7b73ffca51bdba117d6b7e400_
and commit of RMG log is:
_commit 7fbb9e4a62ce6055451efa0262b671b555cad870_
And the error info is:
  **Starting project minimal

/home/svu/e0444166/conda_envs/arc_env/lib/python3.7/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
  File "/home/svu/e0444166/ARC/arc/main.py", line 340, in __init__
    converted_species.append(ARCSpecies(species_dict=spc))
  File "/home/svu/e0444166/ARC/arc/species/species.py", line 508, in __init__
    self.set_mol_list()
  File "/home/svu/e0444166/ARC/arc/species/species.py", line 955, in set_mol_list
    save_order=True,
  File "rmgpy/molecule/molecule.py", line 2101, in rmgpy.molecule.molecule.Molecule.generate_resonance_structures
TypeError: generate_resonance_structures() got an unexpected keyword argument 'save_order'**

This is the example case: minimal. For testing.

**Comment by alongd** [comment]
Please compile RMG. Activate either the arc_env or rmg_env and type `make clean` and then `make` under the `RMG-Py` folder.

**Comment by NUSCondy** [comment]
Hi @alongd ,
I compiled RMG before. Need I compile it everytime I update the codes?
I recompile RMG-Py again now. However, the same porblem showed up agian like the first coment:
  **Running job scan_a340 for DME (pivots: [4, 1, 2, 3], dihedrals: ['4.00', '1.00', '2.00', '3.00'])
Traceback (most recent call last):
  File "/home/svu/e0444166/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/svu/e0444166/ARC/ARC.py", line 65, in main
    arc_object.execute()
  File "/home/svu/e0444166/ARC/arc/main.py", line 569, in execute
    fine_only=self.fine_only,
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 467, in __init__
    self.schedule_jobs()
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 565, in schedule_jobs
    self.spawn_post_opt_jobs(label=label, job_name=job_name)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1250, in spawn_post_opt_jobs
    self.run_scan_jobs(label)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1152, in run_scan_jobs
    self.spawn_directed_scan_jobs(label, rotor_index=i)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 1319, in spawn_directed_scan_jobs
    pivots=pivots)
  File "/home/svu/e0444166/ARC/arc/scheduler.py", line 770, in run_job
    self.job_dict[label][job_type][job.job_name].run()
  File "/home/svu/e0444166/ARC/arc/job/job.py", line 1287, in run
    self.write_input_file()
  File "/home/svu/e0444166/ARC/arc/job/job.py", line 973, in write_input_file
    scans.append(' '.join([str(num) for num in directed_scan]))
TypeError: 'int' object is not iterable**
[error.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7270956/error.txt)

**Comment by alongd** [comment]
You need to compile RMG every time a change was introduced to cythonized files. Users typically aren't aware of this kind of information, so it is recommended to try recompiling every time you update RMG, by simply tiping `make` which is a relatively fast operation, not `make clean` -> `make` which compiles everything.

Please upload your input file, and I'll try to reproduce this error and debug it.

**Comment by NUSCondy** [comment]
Hi @alongd 
Thank you so much. The input file is attached with '.txt
[input.txt](https://github.com/ReactionMechanismGenerator/ARC/files/7271057/input.txt)
'
