### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by calvinp0** [ReactionMechanismGenerator/ARC#645]
**Describe the bug**

```bash
!!! Warning !!! Distance between atoms 5 and 4 (0.967910 A) is suspicious.
[21:10:30] Explicit valence for atom # 1 N, 4, is greater than permitted
Error: :root:Could not update atomtypes for this molecule:
multiplicity -187
1 N u0 p0 c0 {2,D} {3,D} {4,S}
2 O u0 p2 c0 {1,D}
3 O u0 p2 c0 {1,D}
4 O u1 p2 c0 {1,S}

[21:10:30] Explicit valence for atom # 1 N, 4, is greater than permitted
Error: :root:Could not update atomtypes for this molecule:
multiplicity -187
1 N u0 p0 c0 {2,D} {3,D} {4,S}
2 O u0 p2 c0 {1,D}
3 O u0 p2 c0 {1,D}
4 O u1 p2 c0 {1,S}

[21:10:30] Explicit valence for atom # 1 N, 4, is greater than permitted
Traceback (most recent call last):
  File "/home/calvin.p/Code/ARC/ARC.py", line 69, in <module>
    main()
  File "/home/calvin.p/Code/ARC/ARC.py", line 65, in main
    arc_object.execute()
  File "/home/calvin.p/Code/ARC/arc/main.py", line 583, in execute
    fine_only=self.fine_only,
  File "/home/calvin.p/Code/ARC/arc/scheduler.py", line 486, in __init__
    self.schedule_jobs()
  File "/home/calvin.p/Code/ARC/arc/scheduler.py", line 577, in schedule_jobs
    self.spawn_post_opt_jobs(label=label, job_name=job_name)
  File "/home/calvin.p/Code/ARC/arc/scheduler.py", line 1461, in spawn_post_opt_jobs
    self.spawn_ts_jobs()
  File "/home/calvin.p/Code/ARC/arc/scheduler.py", line 1485, in spawn_ts_jobs
    tsg=tsg_index,
  File "/home/calvin.p/Code/ARC/arc/scheduler.py", line 834, in run_job
    job.execute()
  File "/home/calvin.p/Code/ARC/arc/job/adapter.py", line 317, in execute
    self.execute_incore()
  File "/home/calvin.p/Code/ARC/arc/job/adapters/ts/heuristics.py", line 254, in execute_incore
    product_mol_combinations = list(itertools.product(*list(product.mol_list for product in products)))
TypeError: 'NoneType' object is not iterable
```

**How to reproduce**
The last messages of `arc.log`:

```bash
Running local queue job freq_a18072 using gaussian for r_82_[O-][Np][=O]O
Not running an sp job for r_82_[O-][Np][=O]O at wb97xd/def2tzvp, software: gaussian (dft) since the optimization was done at the same level of theory. Using the optimization output to parse the sp energy.
Running local queue job scan_a18074 for pivots [[2, 4]] using gaussian for r_82_[O-][Np][=O]O
Warning: The memory for job tsg0 using heuristics (32 GB) exceeds 95.0% of the the maximum node memory on None. Setting it to 30.40 GB.
Running incore job tsg0 (a18075) using heuristics for TS11
Warning: Could not order atoms in
1 O u0 p2 c+1 {2,S}
2 N u0 p1 c0 {1,S} {3,S} {4,S}
3 O u0 p2 c+1 {2,S}
4 O u0 p2 c+1 {2,S}

Got the following error:
Could not map non isomorphic molecules
```

**Comment by alongd** [comment]
not relevant on current main, the crash site is gone. closing
