### ISSUE TITLE
ARC conda environment is too stiff to create

### ISSUE THREAD

**Issue by wangdu817** [ReactionMechanismGenerator/ARC#707]
I tried to install dependencies of ARC through "conda env create -f environment.yml" , but the dependency is too stiff to be solved, I can not create it correctly. Conda will get stuck in "Solving environment", is there any alternative way to install the dependencies?

**Comment by calvinp0** [comment]
Hi @wangdu817, we suggest you either change the solver for Conda to libmamba, as described [here](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) or you can utilize [mamabaforge](https://github.com/conda-forge/miniforge).

**Comment by wangdu817** [comment]
Hi @calvinp0 ,thank you so much, it works! But after I installed the dependencies, ARC could not run, and gave the following information, do you have any ideal how to fix it?
`ERROR:root:Unable to find specified property fr_Al_COO
ERROR:root:Unable to find specified property fr_Al_OH
ERROR:root:Unable to find specified property fr_Al_OH_noTert
ERROR:root:Unable to find specified property fr_ArN
ERROR:root:Unable to find specified property fr_Ar_COO
ERROR:root:Unable to find specified property fr_Ar_N
ERROR:root:Unable to find specified property fr_Ar_NH
ERROR:root:Unable to find specified property fr_Ar_OH
ERROR:root:Unable to find specified property fr_COO
ERROR:root:Unable to find specified property fr_COO2
ERROR:root:Unable to find specified property fr_C_O
ERROR:root:Unable to find specified property fr_C_O_noCOO
ERROR:root:Unable to find specified property fr_C_S
ERROR:root:Unable to find specified property fr_HOCCN
ERROR:root:Unable to find specified property fr_Imine
ERROR:root:Unable to find specified property fr_NH0
ERROR:root:Unable to find specified property fr_NH1
ERROR:root:Unable to find specified property fr_NH2
ERROR:root:Unable to find specified property fr_N_O
ERROR:root:Unable to find specified property fr_Ndealkylation1
ERROR:root:Unable to find specified property fr_Ndealkylation2
ERROR:root:Unable to find specified property fr_Nhpyrrole
ERROR:root:Unable to find specified property fr_SH
ERROR:root:Unable to find specified property fr_aldehyde
ERROR:root:Unable to find specified property fr_alkyl_carbamate
ERROR:root:Unable to find specified property fr_alkyl_halide
ERROR:root:Unable to find specified property fr_allylic_oxid
ERROR:root:Unable to find specified property fr_amide
ERROR:root:Unable to find specified property fr_amidine
ERROR:root:Unable to find specified property fr_aniline
ERROR:root:Unable to find specified property fr_aryl_methyl
ERROR:root:Unable to find specified property fr_azide
ERROR:root:Unable to find specified property fr_azo
ERROR:root:Unable to find specified property fr_barbitur
ERROR:root:Unable to find specified property fr_benzene
ERROR:root:Unable to find specified property fr_benzodiazepine
ERROR:root:Unable to find specified property fr_bicyclic
ERROR:root:Unable to find specified property fr_diazo
ERROR:root:Unable to find specified property fr_dihydropyridine
ERROR:root:Unable to find specified property fr_epoxide
ERROR:root:Unable to find specified property fr_ester
ERROR:root:Unable to find specified property fr_ether
ERROR:root:Unable to find specified property fr_furan
ERROR:root:Unable to find specified property fr_guanido
ERROR:root:Unable to find specified property fr_halogen
ERROR:root:Unable to find specified property fr_hdrzine
ERROR:root:Unable to find specified property fr_hdrzone
ERROR:root:Unable to find specified property fr_imidazole
ERROR:root:Unable to find specified property fr_imide
ERROR:root:Unable to find specified property fr_isocyan
ERROR:root:Unable to find specified property fr_isothiocyan
ERROR:root:Unable to find specified property fr_ketone
ERROR:root:Unable to find specified property fr_ketone_Topliss
ERROR:root:Unable to find specified property fr_lactam
ERROR:root:Unable to find specified property fr_lactone
ERROR:root:Unable to find specified property fr_methoxy
ERROR:root:Unable to find specified property fr_morpholine
ERROR:root:Unable to find specified property fr_nitrile
ERROR:root:Unable to find specified property fr_nitro
ERROR:root:Unable to find specified property fr_nitro_arom
ERROR:root:Unable to find specified property fr_nitro_arom_nonortho
ERROR:root:Unable to find specified property fr_nitroso
ERROR:root:Unable to find specified property fr_oxazole
ERROR:root:Unable to find specified property fr_oxime
ERROR:root:Unable to find specified property fr_para_hydroxylation
ERROR:root:Unable to find specified property fr_phenol
ERROR:root:Unable to find specified property fr_phenol_noOrthoHbond
ERROR:root:Unable to find specified property fr_phos_acid
ERROR:root:Unable to find specified property fr_phos_ester
ERROR:root:Unable to find specified property fr_piperdine
ERROR:root:Unable to find specified property fr_piperzine
ERROR:root:Unable to find specified property fr_priamide
ERROR:root:Unable to find specified property fr_prisulfonamd
ERROR:root:Unable to find specified property fr_pyridine
ERROR:root:Unable to find specified property fr_quatN
ERROR:root:Unable to find specified property fr_sulfide
ERROR:root:Unable to find specified property fr_sulfonamd
ERROR:root:Unable to find specified property fr_sulfone
ERROR:root:Unable to find specified property fr_term_acetylene
ERROR:root:Unable to find specified property fr_tetrazole
ERROR:root:Unable to find specified property fr_thiazole
ERROR:root:Unable to find specified property fr_thiocyan
ERROR:root:Unable to find specified property fr_thiophene
ERROR:root:Unable to find specified property fr_unbrch_alkane
ERROR:root:Unable to find specified property fr_urea
ERROR:root:Unable to make new descriptors, descriptor generator not installed
ERROR:root:Unable to find specified property fr_Al_COO
ERROR:root:Unable to find specified property fr_Al_OH
ERROR:root:Unable to find specified property fr_Al_OH_noTert
ERROR:root:Unable to find specified property fr_ArN
ERROR:root:Unable to find specified property fr_Ar_COO
ERROR:root:Unable to find specified property fr_Ar_N
ERROR:root:Unable to find specified property fr_Ar_NH
ERROR:root:Unable to find specified property fr_Ar_OH
ERROR:root:Unable to find specified property fr_COO
ERROR:root:Unable to find specified property fr_COO2
ERROR:root:Unable to find specified property fr_C_O
ERROR:root:Unable to find specified property fr_C_O_noCOO
ERROR:root:Unable to find specified property fr_C_S
ERROR:root:Unable to find specified property fr_HOCCN
ERROR:root:Unable to find specified property fr_Imine
ERROR:root:Unable to find specified property fr_NH0
ERROR:root:Unable to find specified property fr_NH1
ERROR:root:Unable to find specified property fr_NH2
ERROR:root:Unable to find specified property fr_N_O
ERROR:root:Unable to find specified property fr_Ndealkylation1
ERROR:root:Unable to find specified property fr_Ndealkylation2
ERROR:root:Unable to find specified property fr_Nhpyrrole
ERROR:root:Unable to find specified property fr_SH
ERROR:root:Unable to find specified property fr_aldehyde
ERROR:root:Unable to find specified property fr_alkyl_carbamate
ERROR:root:Unable to find specified property fr_alkyl_halide
ERROR:root:Unable to find specified property fr_allylic_oxid
ERROR:root:Unable to find specified property fr_amide
ERROR:root:Unable to find specified property fr_amidine
ERROR:root:Unable to find specified property fr_aniline
ERROR:root:Unable to find specified property fr_aryl_methyl
ERROR:root:Unable to find specified property fr_azide
ERROR:root:Unable to find specified property fr_azo
ERROR:root:Unable to find specified property fr_barbitur
ERROR:root:Unable to find specified property fr_benzene
ERROR:root:Unable to find specified property fr_benzodiazepine
ERROR:root:Unable to find specified property fr_bicyclic
ERROR:root:Unable to find specified property fr_diazo
ERROR:root:Unable to find specified property fr_dihydropyridine
ERROR:root:Unable to find specified property fr_epoxide
ERROR:root:Unable to find specified property fr_ester
ERROR:root:Unable to find specified property fr_ether
ERROR:root:Unable to find specified property fr_furan
ERROR:root:Unable to find specified property fr_guanido
ERROR:root:Unable to find specified property fr_halogen
ERROR:root:Unable to find specified property fr_hdrzine
ERROR:root:Unable to find specified property fr_hdrzone
ERROR:root:Unable to find specified property fr_imidazole
ERROR:root:Unable to find specified property fr_imide
ERROR:root:Unable to find specified property fr_isocyan
ERROR:root:Unable to find specified property fr_isothiocyan
ERROR:root:Unable to find specified property fr_ketone
ERROR:root:Unable to find specified property fr_ketone_Topliss
ERROR:root:Unable to find specified property fr_lactam
ERROR:root:Unable to find specified property fr_lactone
ERROR:root:Unable to find specified property fr_methoxy
ERROR:root:Unable to find specified property fr_morpholine
ERROR:root:Unable to find specified property fr_nitrile
ERROR:root:Unable to find specified property fr_nitro
ERROR:root:Unable to find specified property fr_nitro_arom
ERROR:root:Unable to find specified property fr_nitro_arom_nonortho
ERROR:root:Unable to find specified property fr_nitroso
ERROR:root:Unable to find specified property fr_oxazole
ERROR:root:Unable to find specified property fr_oxime
ERROR:root:Unable to find specified property fr_para_hydroxylation
ERROR:root:Unable to find specified property fr_phenol
ERROR:root:Unable to find specified property fr_phenol_noOrthoHbond
ERROR:root:Unable to find specified property fr_phos_acid
ERROR:root:Unable to find specified property fr_phos_ester
ERROR:root:Unable to find specified property fr_piperdine
ERROR:root:Unable to find specified property fr_piperzine
ERROR:root:Unable to find specified property fr_priamide
ERROR:root:Unable to find specified property fr_prisulfonamd
ERROR:root:Unable to find specified property fr_pyridine
ERROR:root:Unable to find specified property fr_quatN
ERROR:root:Unable to find specified property fr_sulfide
ERROR:root:Unable to find specified property fr_sulfonamd
ERROR:root:Unable to find specified property fr_sulfone
ERROR:root:Unable to find specified property fr_term_acetylene
ERROR:root:Unable to find specified property fr_tetrazole
ERROR:root:Unable to find specified property fr_thiazole
ERROR:root:Unable to find specified property fr_thiocyan
ERROR:root:Unable to find specified property fr_thiophene
ERROR:root:Unable to find specified property fr_unbrch_alkane
ERROR:root:Unable to find specified property fr_urea
Traceback (most recent call last):
  File "/home/test/ARC_NEW/ARC.py", line 12, in <module>
    from arc.common import read_yaml_file
  File "/home/test/ARC_NEW/arc/__init__.py", line 2, in <module>
    import arc.main
  File "/home/test/ARC_NEW/arc/main.py", line 21, in <module>
    from arkane.encorr.corr import assign_frequency_scale_factor
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/arkane/__i                                                     nit__.py", line 34, in <module>
    from arkane.common import ArkaneSpecies
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/arkane/com                                                     mon.py", line 62, in <module>
    from arkane.pdep import PressureDependenceJob
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/arkane/pde                                                     p.py", line 43, in <module>
    from rmgpy.chemkin import write_kinetics_entry
  File "rmgpy/chemkin.pyx", line 52, in init rmgpy.chemkin
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/rmgpy/rmg/                                                     pdep.py", line 48, in <module>
    from rmgpy.rmg.react import react_species
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/rmgpy/rmg/                                                     react.py", line 36, in <module>
    from rmgpy.data.rmg import get_db
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/rmgpy/data                                                     /rmg.py", line 42, in <module>
    from rmgpy.data.thermo import ThermoDatabase
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/rmgpy/data                                                     /thermo.py", line 47, in <module>
    from rmgpy.ml.estimator import MLEstimator
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/rmgpy/ml/e                                                     stimator.py", line 36, in <module>
    import chemprop
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/chemprop-0                                                     .0.1-py3.7.egg/chemprop/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/chemprop-0                                                     .0.1-py3.7.egg/chemprop/data/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/chemprop-0                                                     .0.1-py3.7.egg/chemprop/data/data.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/chemprop-0                                                     .0.1-py3.7.egg/chemprop/features/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/chemprop-0                                                     .0.1-py3.7.egg/chemprop/features/features_generators.py", line 95, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/descriptas                                                     torus-2.0.0.32-py3.7.egg/descriptastorus/descriptors/__init__.py", line 3, in <m                                                     odule>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/descriptas                                                     torus-2.0.0.32-py3.7.egg/descriptastorus/descriptors/rdDescriptors.py", line 278                                                     , in <module>
  File "/home/test/anaconda3/envs/arc_env/lib/python3.7/site-packages/descriptas                                                     torus-2.0.0.32-py3.7.egg/descriptastorus/descriptors/rdDescriptors.py", line 271                                                     , in __init__
ValueError: RDKit2D: Failed to initialize: unable to find specified properties:
        fr_Al_COO
        fr_Al_OH
        fr_Al_OH_noTert
        fr_ArN
        fr_Ar_COO
        fr_Ar_N
        fr_Ar_NH
        fr_Ar_OH
        fr_COO
        fr_COO2
        fr_C_O
        fr_C_O_noCOO
        fr_C_S
        fr_HOCCN
        fr_Imine
        fr_NH0
        fr_NH1
        fr_NH2
        fr_N_O
        fr_Ndealkylation1
        fr_Ndealkylation2
        fr_Nhpyrrole
        fr_SH
        fr_aldehyde
        fr_alkyl_carbamate
        fr_alkyl_halide
        fr_allylic_oxid
        fr_amide
        fr_amidine
        fr_aniline
        fr_aryl_methyl
        fr_azide
        fr_azo
        fr_barbitur
        fr_benzene
        fr_benzodiazepine
        fr_bicyclic
        fr_diazo
        fr_dihydropyridine
        fr_epoxide
        fr_ester
        fr_ether
        fr_furan
        fr_guanido
        fr_halogen
        fr_hdrzine
        fr_hdrzone
        fr_imidazole
        fr_imide
        fr_isocyan
        fr_isothiocyan
        fr_ketone
        fr_ketone_Topliss
        fr_lactam
        fr_lactone
        fr_methoxy
        fr_morpholine
        fr_nitrile
        fr_nitro
        fr_nitro_arom
        fr_nitro_arom_nonortho
        fr_nitroso
        fr_oxazole
        fr_oxime
        fr_para_hydroxylation
        fr_phenol
        fr_phenol_noOrthoHbond
        fr_phos_acid
        fr_phos_ester
        fr_piperdine
        fr_piperzine
        fr_priamide
        fr_prisulfonamd
        fr_pyridine
        fr_quatN
        fr_sulfide
        fr_sulfonamd
        fr_sulfone
        fr_term_acetylene
        fr_tetrazole
        fr_thiazole
        fr_thiocyan
        fr_thiophene
        fr_unbrch_alkane
        fr_urea
`

**Comment by alongd** [comment]
arc's conda env was fixed with the Py14 migration, closing this now
